version: '3.8'

services:
  # Servicio de la API NestJS
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rewards-api
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/rewards-platform
    depends_on:
      - mongodb
    networks:
      - rewards-network

  # Servicio de MongoDB
  mongodb:
    image: mongo:5.0
    container_name: rewards-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - rewards-network
    environment:
      - MONGO_INITDB_DATABASE=rewards-platform

  # Servicio de administración de MongoDB (opcional)
  mongo-express:
    image: mongo-express
    container_name: rewards-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      - mongodb
    networks:
      - rewards-network

volumes:
  mongodb_data:

networks:
  rewards-network:
    driver: bridge